#!/usr/bin/env python3
# coding: UTF-8

from run import Server
from case import Case

server = Server()

##############################
server.run("basic.conf")######
##############################

case = Case("nonexist folder", "GET", "http://localhost:4200/abc")
case.status_code(404)
case.body_has("404 Not Found")
case.header_has("Content-Length")


case = Case("index file", "GET", "http://localhost:4200?key1=val1&key2=val2")
case.status_code(200)
case.body_has("html")
case.header_has("Content-Length")


payload = {"key1": "val1", "key2": "val2"} # リクエストヘッダ
case = Case("extra request header", "GET", "http://localhost:4200", headers=payload)
case.status_code(200)
case.body_has("めざせいっかげつ")
case.header_has("Content-Length")


case = Case("post index not allowed", "POST", "http://localhost:4200", body="this is body.")
case.status_code(405)
case.body_is(".*html.*")
case.header_has("Content-Length")


case = Case("post upload", "POST", "http://localhost:4201/upload", body="this is body.")
case.status_code(201)
case.body_has("")
case.header_has("Content-Length")
case.header_has("Content-Location")


case = Case("get upload folder (autoindex)", "GET", "http://localhost:4201/upload")
case.status_code(200)
case.body_has("")
case.header_has("Content-Length")


case = Case("redirect 301", "GET", "http://localhost:4200/kapouet/")
case.status_code(301)
case.header_has("Content-Length")
case.header_has("Location")


case = Case("cgi", "POST", "http://localhost:4200/cgi/perl.py", body="key1=val1&key2=val2")
case.status_code(200)
case.header_has("Content-Length")
case.body_is("<!doctype html>\n<html>\n<head>\n<meta charset=\"utf-8\">\n<title>CGI TEST</title>\n</head>\n<body>\n<h1>CGI TEST</h1>\n<pre>\n.*")

##########################
server.stop() # basic.conf
##########################



#################################
server.run("redirect.conf")######
#################################

case = Case("redirect 301 :5555/a", "GET", "http://localhost:5555/a")
case.status_code(301)
case.header_has("Content-Length")
case.header_has("Location")


case = Case("redirect 302 :5555/b", "GET", "http://localhost:5555/b")
case.status_code(302)
case.header_has("Content-Length")
case.header_has("Location")


case = Case("redirect 303 :5555/c", "GET", "http://localhost:5555/c")
case.status_code(303)
case.header_has("Content-Length")
case.header_has("Location")


case = Case("redirect 307 :5555/d", "GET", "http://localhost:5555/d")
case.status_code(307)
case.header_has("Content-Length")
case.header_has("Location")

#############################
server.stop() # redirect.conf
#############################



###############################
server.run("delete.conf")######
###############################

case = Case("http DELETE", "DELETE", "http://localhost:4200/trash")
case.status_code(204)
case.header_has("Content-Length")

###########################
server.stop() # delete.conf
###########################

