#!/usr/bin/env python3
# coding: UTF-8

from run import Server
from case import Case
import subprocess
import os

server = Server()

##############################
server.run("default.conf")######
##############################

case = Case("get index", "GET", "http://localhost:80/index.html")
case.status_code(200)
case.body_has("めざせいっかげつ")
case.header_has("Content-Length")


case = Case("file with / is 404", "GET", "http://localhost:80/index.html/")
case.status_code(404)
case.body_has("404 Not Found")
case.header_has("Content-Length")


case = Case("nonexist folder", "GET", "http://localhost:80/abc")
case.status_code(404)
case.body_has("404 Not Found")
case.header_has("Content-Length")


case = Case("index file", "GET", "http://localhost:80?key1=val1&key2=val2")
case.status_code(200)
case.body_has("html")
case.header_has("Content-Length")


payload = {"key1": "val1", "key2": "val2"} # リクエストヘッダ
case = Case("extra request header", "GET", "http://localhost:80", headers=payload)
case.status_code(200)
case.body_has("めざせいっかげつ")
case.header_has("Content-Length")


case = Case("post 405", "POST", "http://localhost:80", body="this is body.")
case.status_code(405)
case.body_is(".*html.*")
case.header_has("Content-Length")


case = Case("post redirect", "POST", "http://localhost:8080/upload", body="this is body.")
case.status_code(301)
case.body_has("")
case.header_has("Content-Length")
case.header("Location", "http://127.0.0.1:8080/upload/")


case = Case("post upload", "POST", "http://localhost:8080/upload/", body="this is body.")
case.status_code(201)
case.body_has("")
case.header_has("Content-Length")
case.header_has("Content-Location")


case = Case("redirect get upload folder (autoindex)", "GET", "http://localhost:8080/upload")
case.status_code(301)
case.body_has("")
case.header_has("Content-Length")
case.header("Location", "http://127.0.0.1:8080/upload/")


case = Case("get upload folder (autoindex)", "GET", "http://localhost:8080/upload/")
case.status_code(200)
case.body_has("Index of")
case.header_has("Content-Length")


case = Case("redirect 301", "GET", "http://localhost:80/kapouet/")
case.status_code(301)
case.header_has("Content-Length")
case.header_has("Location")


case = Case("cgi", "POST", "http://localhost:80/cgi/test.py", body="key1=val1&key2=val2")
case.status_code(200)
case.header_has("Content-Length")
case.body_is(".*<TITLE>CGI script output</TITLE>.*")


subprocess.run(("touch", "./docs/html/cant_read"))
os.chmod("./docs/html/cant_read", 660)
case = Case("forbidden file acces", "GET", "http://localhost:80/cant_read")
case.status_code(403)
case.header_has("Content-Length")
case.body_has("403")
subprocess.run(("rm", "./docs/html/cant_read"))

##########################
server.stop() # basic.conf
##########################



#################################
server.run("redirect.conf")######
#################################

case = Case("redirect 301 :5555/a", "GET", "http://localhost:5555/a")
case.status_code(301)
case.header_has("Content-Length")
case.header_has("Location")


case = Case("redirect 302 :5555/b", "GET", "http://localhost:5555/b")
case.status_code(302)
case.header_has("Content-Length")
case.header_has("Location")


case = Case("redirect 303 :5555/c", "GET", "http://localhost:5555/c")
case.status_code(303)
case.header_has("Content-Length")
case.header_has("Location")


case = Case("redirect 307 :5555/d", "GET", "http://localhost:5555/d")
case.status_code(307)
case.header_has("Content-Length")
case.header_has("Location")

#############################
server.stop() # redirect.conf
#############################



###############################
server.run("delete.conf")######
###############################

subprocess.run(("touch", "./docs/html/trash"))
case = Case("http DELETE", "DELETE", "http://localhost:4200/trash")
case.status_code(204)
case.header_has("Content-Length")


case = Case("http DELETE", "DELETE", "http://localhost:4200/trash")
case.status_code(404)
case.header_has("Content-Length")

###########################
server.stop() # delete.conf
###########################
