name: Unit test

on:
  push:
    branches: [main]
  pull_request_:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: unit test
        run: make check
